### PR TITLE
fix(icons): correct handling of tailwind prefix

### LINKED ISSUE #145: Classes are prefixed twice - tailwind config prefix
The icons work fine without a prefix, however once I want to use custom prefix, Rocketicons stop working.

```js
// tailwind.config.js
const icons = require("rocketicons/tailwind");

/** @type {import('tailwindcss').Config} */
export default {
  // content: ["./**/*.{js,jsx,ts,tsx}", "./*.{js,jsx,ts,tsx}"],
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-mode="dark"]'],
  prefix: "a-",
  theme: {
    extend: {},
  },
  plugins: [icons.iconPlugin], // plugins: [icons] doesn't work in Storybook; idk why
};
```
Background and text colours work:
image

Rocketicons intellisense:
image

Using `a-a-icon-current` starts throwing errors like this and the project won't compile: 
```
(2:1) E:\Projects\storybooktest\src\tailwind.css The `p-0` class does not exist. If `p-0` is a custom class, make sure it is defined within a `@layer` directive.

  1 | @tailwind base;
> 2 | @tailwind components;
    | ^
  3 | @tailwind utilities;
  4 | @tailwind variants;
  ```

The project compiles just fine using `a-icon-current`, however no Rocketicons classes are bundled in `tailwind.css`.

### PR DESCRIPTION
**Pull request by programad**
The idea here is to add the prefix to the classes before sending them to the style generator.

This should fix #145

### CODE REVIEW

File: packages/tailwind/src/utils/config-handler.ts [hunk 1]
```diff
@@ -40,13 +40,19 @@ const toShortCutStyles = (theme: ThemeOptions, name: string, color: string) =>
...
     )
   );
 
-const generateConfig = <T extends ThemeOptions>(theme: T, parsedColors: ParsedColors) => {
+const generateConfig = <T extends ThemeOptions>(
+  theme: T,
+  parsedColors: ParsedColors,
+  prefix?: string
+) => {
+  const prefixToAdd = prefix ? prefix : "";
```
Comment (amorimjj) [inline packages/tailwind/src/utils/config-handler.ts:54]: We can move the initialization of the prefix to line 52 change it to `prefix: string = ''` and use the prefix across the code, avoiding to create this new variable

File: packages/tailwind/src/utils/config-handler.ts [hunk 2]
```diff
@@ -57,15 +63,15 @@ const generateConfig = <T extends ThemeOptions>(theme: T, parsedColors: ParsedCo
 
   const colors = () =>
     ([] as StyleHandler[]).concat(
-      ...AVAILABLE_VARIANTS.map((variant) => toColorsStyles(parsedColors, variant))
+      ...AVAILABLE_VARIANTS.map((variant) => toColorsStyles(parsedColors, variant, prefixToAdd))
```
Comment (amorimjj) [inline packages/tailwind/src/utils/config-handler.ts:66]: The suggestion above is because it's a little bit hard to understand how, why and where prefix became prefixToAdd

File: packages/tailwind/src/utils/config-handler.ts [hunk 3]
```diff
@@ -57,15 +63,15 @@ const generateConfig = <T extends ThemeOptions>(theme: T, parsedColors: ParsedCo
...
     );
 
   const sizes = () =>
     ([] as StyleHandler[]).concat(
       ([] as StyleHandler[]).concat(
         ...Object.keys(theme.sizes).map((size) => ({
           name: () => `${size}`,
-          styles: () => sanitize(theme.sizes[size])
+          styles: () => `${sanitize(theme.sizes[size])}`
```
Comment (amorimjj) [inline packages/tailwind/src/utils/config-handler.ts:74]: Not sure, but I don't think the "`" is needed here. I think is safe to remove even from line 73 as well.

**Review by amorimjj — CHANGES_REQUESTED** [review]
Well done! Just few comments

**Comment by programad** [comment]
> Hi, any updates on this PR?

Almost there, sorry for the delay.
